<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="cancer2_files/filelist.xml">
<link rel="stylesheet" href="{{ asset('public/css/estrategia_cancer.css') }}">
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="reporte" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1410 style='border-collapse:
 collapse;table-layout:fixed;width:1058pt'>
 <col width=440 style='mso-width-source:userset;mso-width-alt:16091;width:330pt'>
 <col width=133 style='mso-width-source:userset;mso-width-alt:4864;width:100pt'>
 <col width=361 style='mso-width-source:userset;mso-width-alt:13202;width:271pt'>
 <col width=68 span=3 style='mso-width-source:userset;mso-width-alt:2486;
 width:51pt'>
 <col width=68 style='mso-width-source:userset;mso-width-alt:2486;width:51pt'>
 <col width=68 span=3 style='mso-width-source:userset;mso-width-alt:2486;
 width:51pt'>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1512389 width=440 style='height:15.0pt;width:330pt'></td>
  <td class=xl1512389 width=133 style='width:100pt'></td>
  <td class=xl1512389 width=361 style='width:271pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
  <td class=xl1512389 width=68 style='width:51pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1512389 style='height:15.0pt'></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr class=xl7212389 height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7512389 style='height:15.0pt'>ACTIVIDAD</td>
  <td class=xl7512389 style='border-left:none'>RESULTADO</td>
  <td class=xl7512389 style='border-left:none'>TOTAL</td>
  <td class=xl7512389 style='border-left:none'>&lt;20a</td>
  <td class=xl7512389 style='border-left:none'>20-29a</td>
  <td class=xl7512389 style='border-left:none'>30-39a</td>
  <td class=xl7512389 style='border-left:none'>40-49a</td>
  <td class=xl7512389 style='border-left:none'>50-59a</td>
  <td class=xl7512389 style='border-left:none'>60-69a</td>
  <td class=xl7512389 style='border-left:none'>70 y más</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1512389 style='height:15.0pt'></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8612389 style='height:15.0pt'>MUJERES TAMIZADAS EN
  CANCER DE CUELLO UTERINO</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8912389>&nbsp;</td>
  <td class=xl8912389>&nbsp;</td>
  <td class=xl8912389>&nbsp;</td>
  <td class=xl8912389>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl12612389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Persona examinada con papanicolaou</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10212389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10112389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl12612389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Persona examinada con Inspección Visual Acido
  Acético</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10112389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl12812389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Detección molecular de Virus Papiloma Humano</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8212389 style='height:15.0pt;border-top:none'>&nbsp;</td>
  <td class=xl8812389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8612389 style='height:15.0pt'>MUJERES TAMIZADAS EN
  CANCER DE MAMA</td>
  <td class=xl8512389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13012389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Examen clínico de mama</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13012389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Mujer tamizada con mamografía bilateral de
  tamizaje</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13012389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Mujer con mamografía durante tratamiento o
  post tratamiento</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl9012389 style='height:15.0pt;border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8812389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl9112389 style='height:15.0pt'>PERSONAS TAMIZADAS PARA
  DETECCION DE OTROS CANCER</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl9212389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13012389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Tamizaje para detección de cáncer de colon y
  recto</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl11912389 style='height:15.0pt;border-top:none'>Tamizaje
  para detección de cáncer de próstata</td>
  <td class=xl11712389 style='border-top:none'>&nbsp;</td>
  <td class=xl11812389 style='border-top:none'>&nbsp;</td>
  <td class=xl10312389 style='border-top:none'>&nbsp;</td>
  <td class=xl8712389 style='border-top:none'>&nbsp;</td>
  <td class=xl8712389 style='border-top:none'>&nbsp;</td>
  <td class=xl8712389 style='border-top:none'>&nbsp;</td>
  <td class=xl8712389 style='border-top:none'>&nbsp;</td>
  <td class=xl8712389 style='border-top:none'>&nbsp;</td>
  <td class=xl8712389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13212389 style='height:30.0pt'><span
  style='mso-spacerun:yes'>    </span>Examen de tacto rectal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13212389 style='border-bottom:.5pt solid black;
  height:30.0pt'><span style='mso-spacerun:yes'>    </span>Examen PSA</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13512389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Tamizaje para detección de cáncer de piel</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl9012389 style='height:15.0pt;border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10512389 style='height:15.0pt'>PERSONA ATENDIDA CON
  LESIONES PRE MALIGNAS DE CANCER DE CUE<span style='display:none'>LLO UTERINO</span></td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10612389 style='height:15.0pt'>ACTIVIDAD</td>
  <td class=xl10712389 style='border-top:none'>GRUPO RIESGO</td>
  <td class=xl10612389>TOTAL</td>
  <td class=xl10612389 style='border-left:none'>&lt;20a</td>
  <td class=xl10612389 style='border-left:none'>20-29a</td>
  <td class=xl10612389 style='border-left:none'>30-39a</td>
  <td class=xl10612389 style='border-left:none'>40-49a</td>
  <td class=xl10612389 style='border-left:none'>50-59a</td>
  <td class=xl10612389 style='border-left:none'>60-69a</td>
  <td class=xl10612389 style='border-left:none'>70 y más</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13312389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>Mujer examinada con colposcopia</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>Normal</td>
  <td class=xl10412389 style='border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10012389 style='height:15.0pt;border-top:none;
  border-left:none'>Anormal</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7112389 style='height:15.0pt;border-top:none'>Atención
  de pacientes con lesiones premalignas de cuello uterino con ablación</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>30 a 49 años</td>
  <td class=xl10412389 style='border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7112389 style='height:15.0pt;border-top:none'>Atención
  de pacientes con lesiones premalignas de cuello uterino con tratamiento
  escisional</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>30 a 64 años</td>
  <td class=xl10412389 style='border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1512389 style='height:15.0pt'></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12012389 style='height:15.0pt'>PROCEDIMIENTOS PARA EL
  DIAGNOSTICO DE CANCER</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr class=xl7312389 height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7112389 style='height:15.0pt'>Persona atendida con
  procedimiento de biopsia de Cuello Uterino</td>
  <td class=xl7112389 style='border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
  <td class=xl6612389 style='border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7412389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia mamaria</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12112389 style='height:15.0pt'>Persona atendida con
  procedimiento de biopsia de prostata</td>
  <td class=xl12112389 style='border-top:none;border-left:none'>Todas las
  edades</td>
  <td class=xl12212389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia de colon recto</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia de estómago</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia de piel</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia pulmonar</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia de hígado</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia de ganglios</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de Aspirado de Médula ósea</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de biopsia de médula ósea</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  atendida con procedimiento de punción lumbar</td>
  <td class=xl7112389 style='border-top:none;border-left:none'>Todas las edades</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6512389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8112389 style='height:15.0pt;border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8312389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
  <td class=xl8212389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8612389 style='height:15.0pt'>ATENCION DE CANCER</td>
  <td class=xl1512389></td>
  <td class=xl10812389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td rowspan=2 height=40 class=xl13912389 style='border-bottom:.5pt solid black;
  height:30.0pt;border-top:none'>DIAGNOSTICO DE CANCER</td>
  <td rowspan=2 class=xl12412389 style='border-bottom:.5pt solid white'>TOTAL
  CASOS</td>
  <td colspan=4 class=xl13712389 style='border-right:.5pt solid white;
  border-left:none'>ESTADIO</td>
  <td rowspan=2 class=xl12412389 style='border-bottom:.5pt solid white'>TRATAM</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl10912389 style='height:15.0pt'>1</td>
  <td class=xl10612389 style='border-top:none'>2</td>
  <td class=xl10912389>3</td>
  <td class=xl10612389 style='border-top:none'>4</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de cuello uterino</td>
  <td class=xl10412389 style='border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl11012389 style='border-left:none'>&nbsp;</td>
  <td class=xl10412389 style='border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de mama</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de estómago</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de próstata</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de pulmón</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de colon y recto</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de hígado</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Leucemia</td>
  <td class=xl11112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Linforma</td>
  <td class=xl11112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Cáncer
  de piel</td>
  <td class=xl11112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl10112389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl11312389 style='height:15.0pt'></td>
  <td class=xl11412389>&nbsp;</td>
  <td class=xl11512389></td>
  <td class=xl11612389></td>
  <td class=xl11612389></td>
  <td class=xl11612389></td>
  <td class=xl10812389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
  <td class=xl1512389></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl7512389 style='height:15.0pt'>ACTIVIDAD</td>
  <td class=xl7512389 style='border-left:none'>UNIDAD DE MEDIDA</td>
  <td class=xl7512389 style='border-left:none'>TOTAL</td>
  <td class=xl7512389 style='border-left:none'>&lt;20a</td>
  <td class=xl7512389 style='border-left:none'>20-29a</td>
  <td class=xl7512389 style='border-left:none'>30-39a</td>
  <td class=xl7512389 style='border-left:none'>40-49a</td>
  <td class=xl7512389 style='border-left:none'>50-59a</td>
  <td class=xl7512389 style='border-left:none'>60-69a</td>
  <td class=xl7512389 style='border-left:none'>70 y más</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8012389 style='height:15.0pt;border-top:none'>PERSONA
  CON CONSEJERIA PARA LA PREVENCION Y CONTROL DEL CAN<span style='display:none'>CER</span></td>
  <td class=xl7012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7612389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7712389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl7912389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Consejería
  preventiva en factores de riesgo para el cáncer</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Consejería</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6712389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Consejería
  para pacientes diagnosticados con cáncer</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Consejería</td>
  <td class=xl11212389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6712389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8112389 style='height:15.0pt;border-top:none'>&nbsp;</td>
  <td class=xl8812389 style='border-top:none'>&nbsp;</td>
  <td class=xl9312389 style='border-top:none'>&nbsp;</td>
  <td class=xl9412389 style='border-top:none'>&nbsp;</td>
  <td class=xl9512389 style='border-top:none'>&nbsp;</td>
  <td class=xl9512389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8612389 style='height:15.0pt'>CUIDADOS PALIATIVOS</td>
  <td class=xl8512389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl9712389>&nbsp;</td>
  <td class=xl9812389>&nbsp;</td>
  <td class=xl9812389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Atención
  con cuidados paliativos en el establecimiento de salud</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Atención</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6712389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Atención
  con cuidados paliativos en el domicilio</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Atención</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6712389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8112389 style='height:15.0pt;border-top:none'>&nbsp;</td>
  <td class=xl8812389 style='border-top:none'>&nbsp;</td>
  <td class=xl9312389 style='border-top:none'>&nbsp;</td>
  <td class=xl9412389 style='border-top:none'>&nbsp;</td>
  <td class=xl9512389 style='border-top:none'>&nbsp;</td>
  <td class=xl9512389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
  <td class=xl9612389 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl8612389 style='height:15.0pt'>TOMA DE MUESTRA PAP</td>
  <td class=xl8512389>&nbsp;</td>
  <td class=xl8412389>&nbsp;</td>
  <td class=xl9712389>&nbsp;</td>
  <td class=xl9812389>&nbsp;</td>
  <td class=xl9812389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
  <td class=xl9912389>&nbsp;</td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl12312389 style='height:15.0pt;border-top:none'>Persona
  examinada con papanicolaou</td>
  <td class=xl7012389 style='border-top:none;border-left:none'>Atención</td>
  <td class=xl10012389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6712389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6812389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
  <td class=xl6912389 style='border-top:none;border-left:none'>&nbsp;</td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=440 style='width:330pt'></td>
  <td width=133 style='width:100pt'></td>
  <td width=361 style='width:271pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=68 style='width:51pt'></td>
  <td width=68 style='width:51pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->

<script src="{{ url('/node_modules/axios/dist/axios.min.js') }}"></script>
<script src="{{ url('/node_modules/vue/dist/vue.min.js') }}"></script>
<script src="{{ url('/resources/assets/js/indicadores/appCancerReporte.js') }}"></script>

</body>

</html>
