<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<title>ACTIVIDADADES DE LA ESTRATEGIA SANITARIA DE SALUD OCULAR</title>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="213_Reporte_Ocular_Fto20141_files/filelist.xml">
<!--[if !mso]>
<style>
v\:* {behavior:url(#default#VML);}
o\:* {behavior:url(#default#VML);}
x\:* {behavior:url(#default#VML);}
.shape {behavior:url(#default#VML);}
</style>
<![endif]-->
<link rel="stylesheet" href="{{ asset('public/css/salud_ocular.css') }}">

</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="reporte" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1085 class=xl6510219
 style='border-collapse:collapse;table-layout:fixed;width:819pt'>
 <col class=xl6510219 width=433 style='mso-width-source:userset;mso-width-alt:
 15835;width:325pt'>
 <col class=xl6510219 width=62 style='mso-width-source:userset;mso-width-alt:
 2267;width:47pt'>
 <col class=xl10210219 width=70 span=8 style='mso-width-source:userset;
 mso-width-alt:2560;width:53pt'>
 <col class=xl6510219 width=30 style='mso-width-source:userset;mso-width-alt:
 1097;width:23pt'>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 width=433 style='height:15.0pt;width:325pt' align=left
  valign=top>
  <![if !vml]><span style='mso-ignore:vglayout;
  position:absolute;z-index:1;margin-left:3px;margin-top:0px;width:288px;
  height:38px'><img width=288 height=38
  src="{{ asset('public/ministerio_de_salud_logo.png') }}"
  alt="Descripción: OGEI" v:shapes="_x0031__x0020_Imagen"></span><![endif]><span
  style='mso-ignore:vglayout2'>
  <table cellpadding=0 cellspacing=0>
   <tr>
    <td height=20 class=xl6510219 width=433 style='height:15.0pt;width:325pt'></td>
   </tr>
  </table>
  </span></td>
  <td class=xl6510219 width=62 style='width:47pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl10210219 width=70 style='width:53pt'></td>
  <td class=xl6510219 width=30 style='width:23pt'></td>
 </tr>
 <tr height=20 style='mso-height-source:userset;height:15.0pt'>
  <td height=20 class=xl9410219 style='height:15.0pt'></td>
  <td class=xl9310219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=31 style='height:23.25pt'>
  <td colspan=10 height=31 class=xl14010219 style='height:23.25pt'>REPORTE
  MENSUAL DE LAS ACTIVIDADADES DE LA ESTRATEGIA SANITARIA DE SALUD OCULAR</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl9210219 style='height:12.75pt'>Periodo :<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl13610219 colspan=2>@{{startDate}} - @{{endDate}}</td>
  <td class=xl10210219></td>
  <td class=xl13610219></td>
  <td class=xl13610219></td>
  <td class=xl13610219></td>
  <td class=xl13610219></td>
  <td class=xl13610219></td>
  <td class=xl13610219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl9210219 style='height:12.75pt'>DIRESA / RED / M. Red /
  EE.SS :</td>
  <td class=xl13610219 colspan=2>DIRESA APURIMAC</td>
  <td class=xl10210219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl10210219 style='height:12.75pt'></td>
  <td class=xl13610219 colspan=5>Edad Según ETAPAS DE VIDA /<span
  style='mso-spacerun:yes'>  </span>Ambito : TODOS LOS EE.SS ;<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13710219></td>
  <td class=xl13810219></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl6510219 style='height:12.75pt'></td>
  <td class=xl6510219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl6610219></td>
  <td class=xl10310219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=32 style='mso-height-source:userset;height:24.0pt'>
  <td rowspan=2 height=64 class=xl14410219 width=433 style='border-bottom:.5pt solid #7030A0;
  height:48.0pt;width:325pt'>DIAGNÓSTICO / ACTIVIDADES</td>
  <td rowspan=2 class=xl9510219 width=62 style='border-bottom:.5pt solid #7030A0;
  width:47pt'>TOTAL</td>
  <td colspan=3 class=xl14110219 width=210 style='border-right:.5pt solid white;
  border-left:none;width:159pt'>Niño</td>
  <td class=xl6710219 width=70 style='border-left:none;width:53pt'>Adolescente</td>
  <td class=xl9510219 width=70 style='border-left:none;width:53pt'>Joven</td>
  <td colspan=2 class=xl14710219 width=140 style='border-right:.5pt solid white;
  border-left:none;width:106pt'>Adulto</td>
  <td class=xl6810219 width=70 style='border-left:none;width:53pt'>A. Mayor</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=32 style='mso-height-source:userset;height:24.0pt'>
  <td height=32 class=xl6910219 width=70 style='height:24.0pt;border-left:none;
  width:53pt'>01d - 02a</td>
  <td class=xl6910219 width=70 style='border-left:none;width:53pt'>03a - 05a</td>
  <td class=xl6910219 width=70 style='border-left:none;width:53pt'>06a - 11a</td>
  <td class=xl6910219 width=70 style='border-left:none;width:53pt'>12a - 17a</td>
  <td class=xl6910219 width=70 style='border-left:none;width:53pt'>18a - 29a</td>
  <td class=xl6910219 width=70 style='border-top:none;border-left:none;
  width:53pt'>30a - 49a</td>
  <td class=xl7010219 width=70 style='border-top:none;border-left:none;
  width:53pt'>50a - 59a</td>
  <td class=xl7110219 width=70 style='width:53pt'>60a + Años</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7210219 style='height:18.0pt;border-top:none'>TAMIZAJE
  Y DETECCIÓN</td>
  <td class=xl7310219 style='border-top:none'>&nbsp;</td>
  <td class=xl10410219 style='border-top:none'>&nbsp;</td>
  <td class=xl10410219 style='border-top:none'>&nbsp;</td>
  <td class=xl10510219 style='border-top:none'>&nbsp;</td>
  <td class=xl10610219 width=70 style='border-top:none;width:53pt'>&nbsp;</td>
  <td class=xl10610219 width=70 style='border-top:none;width:53pt'>&nbsp;</td>
  <td class=xl10610219 width=70 style='border-top:none;width:53pt'>&nbsp;</td>
  <td class=xl10610219 width=70 style='border-top:none;width:53pt'>&nbsp;</td>
  <td class=xl10710219 width=70 style='border-top:none;width:53pt'>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>99173 Determinación de la
  Agudeza Visual (Técnico capacitado)</td>
  <td class=xl9810219>777777</td>
  <td class=xl10810219>74</td>
  <td class=xl10810219>910</td>
  <td class=xl10810219>2,878</td>
  <td class=xl10810219>1,364</td>
  <td class=xl10810219>232</td>
  <td class=xl10810219>77</td>
  <td class=xl10810219>38</td>
  <td class=xl10910219>680</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7510219 style='height:18.0pt'>Z010<span
  style='mso-spacerun:yes'>  </span>Examen de los Ojos y de la Visión<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>8,082</td>
  <td class=xl10810219>122</td>
  <td class=xl10810219>1,088</td>
  <td class=xl10810219>3,187</td>
  <td class=xl10810219>2,293</td>
  <td class=xl10810219>473</td>
  <td class=xl10810219>79</td>
  <td class=xl10810219>38</td>
  <td class=xl10910219>802</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7510219 style='height:18.0pt'>99401 Consejería Integral</td>
  <td class=xl9810219>3,293</td>
  <td class=xl10810219>10</td>
  <td class=xl10810219>614</td>
  <td class=xl10810219>1,731</td>
  <td class=xl10810219>322</td>
  <td class=xl10810219>183</td>
  <td class=xl10810219>117</td>
  <td class=xl10810219>37</td>
  <td class=xl10910219>279</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7510219 style='height:18.0pt'>Z006 Normal (SO en
  LAB)<span style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>3,353</td>
  <td class=xl10810219>17</td>
  <td class=xl10810219>671</td>
  <td class=xl10810219>1,817</td>
  <td class=xl10810219>624</td>
  <td class=xl10810219>72</td>
  <td class=xl10810219>42</td>
  <td class=xl10810219>9</td>
  <td class=xl10910219>101</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>92250 Examen de fondo de
  ojo (Oftalmoscopia Directa)</td>
  <td class=xl9810219>4</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>4</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>CATEGORÍA DE DISCAPACIDAD
  VISUAL (a través de Agudeza Visual)</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11110219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7710219 style='height:18.0pt'>Ojo Derecho Normal (20/20
  a 20/30)</td>
  <td class=xl9810219>4,843</td>
  <td class=xl10810219>55</td>
  <td class=xl10810219>834</td>
  <td class=xl10810219>2,276</td>
  <td class=xl11310219>1,165</td>
  <td class=xl10810219>207</td>
  <td class=xl10810219>76</td>
  <td class=xl10810219>21</td>
  <td class=xl10910219>209</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7710219 style='height:18.0pt'>Ojo Izquierdo Normal
  (20/20 a 20/30)</td>
  <td class=xl9810219>4,550</td>
  <td class=xl10810219>45</td>
  <td class=xl10810219>785</td>
  <td class=xl10810219>2,454</td>
  <td class=xl11310219>883</td>
  <td class=xl10810219>104</td>
  <td class=xl10810219>70</td>
  <td class=xl10810219>20</td>
  <td class=xl10910219>189</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7810219 style='height:18.0pt'>Ojo Derecho Limitación
  visual leve (20/40 a 20/60)</td>
  <td class=xl10010219>243</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>27</td>
  <td class=xl11410219>8</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>12</td>
  <td class=xl11510219>193</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7810219 style='height:18.0pt'>Ojo Izquierdo Limitación
  visual leve (20/40 a 20/60)</td>
  <td class=xl10010219>232</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>2</td>
  <td class=xl11410219>51</td>
  <td class=xl11410219>9</td>
  <td class=xl11410219>2</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>12</td>
  <td class=xl11510219>155</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7710219 style='height:18.0pt'>Ojo Derecho Limitación
  visual moderada (20/70 a 20/200)</td>
  <td class=xl9810219>186</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>21</td>
  <td class=xl10810219>5</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>5</td>
  <td class=xl10910219>153</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7710219 style='height:18.0pt'>Ojo Izquierdo Limitación
  visual moderada (20/70 a 20/200)</td>
  <td class=xl9810219>180</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>22</td>
  <td class=xl10810219>6</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>6</td>
  <td class=xl10910219>145</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7810219 style='height:18.0pt'>Ojo Derecho Limitación
  visual severa (&lt; 20/200 a 20/400)</td>
  <td class=xl10010219>37</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11510219>37</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7810219 style='height:18.0pt'>Ojo Izquierdo Limitación
  visual severa (&lt; 20/200 a 20/400)</td>
  <td class=xl10010219>6</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11510219>5</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7710219 style='height:18.0pt'>Ojo Derecho Ceguera (&lt;
  20/400 a NPL1/)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7710219 style='height:18.0pt'>Ojo Izquierdo Ceguera
  (&lt; 20/400 a NPL1/)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>DETERMINACIÓN DE LA
  PRESIÓN INTRAOCULAR</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11110219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Ojo Derecho Normal (10 –
  20 mm Hg)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl11310219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Ojo Derecho Anormal (&gt;
  20 mm Hg)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl11310219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Ojo Izquierdo Normal (10
  – 20 mm Hg)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl11310219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Ojo Izquierdo Anormal
  (&gt; 20 mm Hg)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl11310219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8010219 style='height:18.0pt'>PATOLOGÍAS</td>
  <td class=xl9710219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11710219 width=70 style='width:53pt'>&nbsp;</td>
  <td class=xl11710219 width=70 style='width:53pt'>&nbsp;</td>
  <td class=xl11710219 width=70 style='width:53pt'>&nbsp;</td>
  <td class=xl11710219 width=70 style='width:53pt'>&nbsp;</td>
  <td class=xl11810219 width=70 style='width:53pt'>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>H543 Discapacidad visual
  leve</td>
  <td class=xl9810219>180</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>2</td>
  <td class=xl10810219>51</td>
  <td class=xl10810219>13</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>6</td>
  <td class=xl10810219>11</td>
  <td class=xl10910219>97</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl8110219 width=433 style='height:25.5pt;width:325pt'>H546
  Disminución Indeterminada de la Agudeza Visual de un ojo (Discapacidad visual
  moderada, monocular)</td>
  <td class=xl10010219>141</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>3</td>
  <td class=xl11410219>15</td>
  <td class=xl11410219>4</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>0</td>
  <td class=xl11510219>118</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl8210219 width=433 style='height:25.5pt;width:325pt'>H542
  Disminución Indeterminada de la Agudeza Visual en ambos ojos (Discapacidad
  visual moderada, binocular)</td>
  <td class=xl9810219>212</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>19</td>
  <td class=xl10810219>5</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>3</td>
  <td class=xl10910219>183</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8110219 width=433 style='height:18.0pt;width:325pt'>H545
  Discapacidad visual grave, monocular<span style='mso-spacerun:yes'> </span></td>
  <td class=xl10010219>9</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>1</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>2</td>
  <td class=xl11410219>1</td>
  <td class=xl11510219>5</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>H541 Discapacidad visual
  grave, binocular</td>
  <td class=xl9810219>12</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>2</td>
  <td class=xl10910219>7</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8110219 width=433 style='height:18.0pt;width:325pt'>H544
  Ceguera de un ojo (ceguera monocular)</td>
  <td class=xl10010219>11</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>0</td>
  <td class=xl11410219>2</td>
  <td class=xl11410219>0</td>
  <td class=xl11510219>9</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>H540 Ceguera en ambos
  ojos (ceguera binocular)</td>
  <td class=xl9810219>5</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>4</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>REFERENCIA DE PACIENTES</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Pacientes Referidos para
  Diagnóstico</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8310219 style='height:18.0pt'>Pacientes Referidos que
  llegaron a EESS para Diagnóstico</td>
  <td class=xl10110219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl12010219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7210219 style='height:18.0pt;border-top:none'>DIAGNÓSTICO
  DE CEGUERA POR CATARATA</td>
  <td class=xl9610219 style='border-top:none'>&nbsp;</td>
  <td class=xl12110219 style='border-top:none'>&nbsp;</td>
  <td class=xl12110219 style='border-top:none'>&nbsp;</td>
  <td class=xl12110219 style='border-top:none'>&nbsp;</td>
  <td class=xl12210219 style='border-top:none'>&nbsp;</td>
  <td class=xl12210219 style='border-top:none'>&nbsp;</td>
  <td class=xl12210219 style='border-top:none'>&nbsp;</td>
  <td class=xl12210219 style='border-top:none'>&nbsp;</td>
  <td class=xl12310219 style='border-top:none'>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>PROCEDIMIENTOS</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8410219 width=433 style='height:18.0pt;width:325pt'>99173
  Determinación de la Agudeza Visual</td>
  <td class=xl9810219>25</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>2</td>
  <td class=xl10910219>22</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>92100 Determinación de la
  Presión Intraocular Bilateral</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>76516 Biometría ocular
  por ultrasonido</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>82947 Glucosa
  cuantitativa en sangre</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>DIAGNÓSTICOS</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H250 Catarata Senil
  Incipiente</td>
  <td class=xl9810219>4</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>4</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H251 Catarata Senil
  Nuclear</td>
  <td class=xl9810219>2</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>2</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H252 Catarata Senil, Tipo
  Morgagnian</td>
  <td class=xl9810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H258 Otras Cataratas
  Seniles</td>
  <td class=xl9810219>1</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>1</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H259 Catarata Senil, no
  Especificada</td>
  <td class=xl9810219>29</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>29</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H260 Catarata Infantil,
  Juvenil y Presenil</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13210219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border-top:none;border-right:.5pt solid #7030A0;
  border-bottom:none;border-left:none;background:#BFBFBF;mso-pattern:black none'>1</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H261 Catarata Traumática</td>
  <td class=xl9810219>2</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>2</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H262 Catarata Complicada</td>
  <td class=xl9810219>2</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10910219>1</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H263 Catarata Inducida
  por drogas</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H264 Catarata Residual</td>
  <td class=xl9810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>1</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H268 Otras Formas
  Especificadas de Catarata</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H269 Catarata, no
  Especificada</td>
  <td class=xl9810219>13</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>2</td>
  <td class=xl10910219>9</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H280 Catarata diabética</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H400 Sospecha de Glaucoma
  (Hipertensión ocular)</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>H409 Glaucoma, no
  Especificado</td>
  <td class=xl9810219>11</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>3</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>7</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8010219 style='height:18.0pt'>TRATAMIENTO DE CEGUERA
  POR CATARATA</td>
  <td class=xl9710219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12510219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>66982 Extracción de
  catarata extracapsular con implante de lente intraocular</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 1 =
  Bajo</td>
  <td class=xl9810219>6</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10910219>5</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 2 =
  Moderado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 3 =
  Alto</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>66850 Facofragmentación
  (mecánica o ultrasonido) con aspiración</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 1 =
  Bajo</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 2 =
  Moderado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 3 =
  Alto</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>66821 Cirugía láser para
  escisión de catarata</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 1 =
  Bajo</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 2 =
  Moderado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 3 =
  Alto</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 colspan=10 style='height:18.0pt;border-right:
  .5pt solid #7030A0'>66820 Discision (Incision) de Catarata Membranosa
  Secundaria (Opacidad Capsular Posterior y/o Hialoideanterior); Técnica con
  Instrumento Cortante (Cuchillo de Ziegler o Wheeler)</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 1 =
  Bajo</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 2 =
  Moderado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 3 =
  Alto</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 colspan=9 style='height:18.0pt'>66830
  Extirpacion de Catarata Membranosa Secundaria (Opacidad Capsular Posterior
  y/o Hialoide Anterior) Conseccion Corneo-Escleral, con o sin Iridectomia
  (Iridocapsulotomia)</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 1 =
  Bajo</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 2 =
  Moderado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 3 =
  Alto</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 colspan=4 style='height:18.0pt'>66984
  Extirpacion de Catarata Extracapsular con Insercion de Protesis de Cristalino
  Intraocular Facoemulsificacion)</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 1 =
  Bajo</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 2 =
  Moderado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Grado de Dificultad 3 =
  Alto</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8010219 style='height:18.0pt'>CONSEJERÍA PARA CONTROL Y
  DETECCIÓN OPORTUNA DE CATARATA</td>
  <td class=xl9710219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12510219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>99401 Consejería Integral
  1º<span style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>13</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>13</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7410219 style='height:18.0pt'>99401 Consejería Integral
  2º<span style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7610219 style='height:18.0pt'>Z488 Controles Post
  Operatorios</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11210219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Pacientes con 1º Control
  Post Operatorio</td>
  <td class=xl9810219>7</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10910219>6</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Pacientes con 2º Control
  Post Operatorio</td>
  <td class=xl9810219>6</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10910219>5</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Pacientes con 3º Control
  Post Operatorio</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Pacientes con 4º Control
  Post Operatorio</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Pacientes con 5 a +
  Controles Post Operatorio</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10910219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl7910219 style='height:18.0pt'>Determinación de la
  Agudeza Visual</td>
  <td class=xl9810219>13</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>2</td>
  <td class=xl10910219>11</td>
  <td class=xl6510219></td>
 </tr>
 <tr class=xl8510219 height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8310219 style='height:18.0pt'>Determinación de la
  Presión Intraocular Bilateral</td>
  <td class=xl10110219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl11910219>0</td>
  <td class=xl12010219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl6510219 style='height:18.0pt'></td>
  <td class=xl9810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8610219 colspan=3 style='height:18.0pt'>CONTROL Y
  TRATAMIENTO ESPECIALIZADO DE COMPLICACIONES POST QUIRÚRGICAS CON UVEÍTIS</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12610219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H590 Síndrome vítreo
  consecutivo a cirugía de catarata</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl12710219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H598 Otros trastornos del
  ojo y sus anexos, consecutivos a procedimientos</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl12710219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8810219 style='height:18.0pt'>&nbsp;</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl10810219></td>
  <td class=xl12710219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8610219 colspan=4 style='height:18.0pt'>TAMIZAJE,
  DIAGNOSTICO Y TRATAMIENTO DEL RECIÉN NACIDO CON RETINOPATÍA DE LA
  PREMATURIDAD</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12610219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H351 Retinopatía de la
  prematuridad</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>92225 Oftalmoscopia
  Indirecta</td>
  <td class=xl9810219>6</td>
  <td class=xl10810219>6</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>67227 Destrucción de
  retinopatía extensa</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>Z489 Control Post
  Operatorio de RN con retinopatía de la Prematuridad</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8610219 style='height:18.0pt'>TAMIZAJE Y DETECCIÓN DE
  ERRORES REFRACTIVOS EN NIÑOS</td>
  <td class=xl9710219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl11610219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12410219>&nbsp;</td>
  <td class=xl12610219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8910219 style='height:18.0pt'>Evaluación visual en
  Niños (hasta 3 años) en Establecimientos de Salud</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl12810219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H539 Alteración Visual No
  Especificada</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8910219 colspan=3 style='height:18.0pt'>Tamizaje de
  Errores Refractivos en Niños (mayores de 3 años) en Establecimientos de Salud</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl12810219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl9010219 width=433 style='height:25.5pt;width:325pt'>H542
  Disminución Indeterminada de la Agudeza Visual en ambos ojos (Discapacidad
  visual moderada, binocular)<span style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>19</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>5</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>3</td>
  <td class=xl13310219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border-top:none;border-right:.5pt solid windowtext;
  border-bottom:none;border-left:none;background:#BFBFBF;mso-pattern:black none'>183</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl9010219 width=433 style='height:25.5pt;width:325pt'>H546
  Disminución Indeterminada de la Agudeza Visual de un ojo (Discapacidad visual
  moderada, monocular)</td>
  <td class=xl9810219>3</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>3</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>15</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>4</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border-top:none;border-right:.5pt solid windowtext;
  border-bottom:none;border-left:none;background:#BFBFBF;mso-pattern:black none'>118</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8910219 style='height:18.0pt'>Tamizaje de Errores
  Refractivos en Instituciones Educativas</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl12810219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>99173 Determinación de la
  Agudeza Visual Bilateral</td>
  <td class=xl9810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H539 Alteración Visual No
  Especificada</td>
  <td class=xl9810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl9010219 width=433 style='height:25.5pt;width:325pt'>H542
  Disminución Indeterminada de la Agudeza Visual en ambos ojos (Discapacidad
  visual moderada, binocular)<span style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl9010219 width=433 style='height:25.5pt;width:325pt'>H546
  Disminución Indeterminada de la Agudeza Visual de un ojo (Discapacidad visual
  moderada, monocular)</td>
  <td class=xl9810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8910219 style='height:18.0pt'>Evaluación y Despistaje
  de Errores Refractivos en niños en niños de 0 a 11 años</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl12810219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=34 style='height:25.5pt'>
  <td height=34 class=xl9010219 width=433 style='height:25.5pt;width:325pt'>H538
  Otras Alteraciones Visuales: Leucocoria, Anormalidades en la inspección, No
  fijación</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H509 Estrabismo</td>
  <td class=xl9810219>2</td>
  <td class=xl10810219>2</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H359 Patologías Retinales</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H179 Cicatriz Corneal</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H028 / H029 Enfermedad
  del Parpado</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H527 Ametropía</td>
  <td class=xl9810219>9</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>1</td>
  <td class=xl10810219>3</td>
  <td class=xl10810219>5</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>5</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>3</td>
  <td class=xl13310219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border-top:none;border-right:.5pt solid windowtext;
  border-bottom:none;border-left:none;background:#BFBFBF;mso-pattern:black none'>12</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8910219 style='height:18.0pt'>Diagnostico y Tratamiento
  de Errores Refractivos</td>
  <td class=xl9910219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl11010219>&nbsp;</td>
  <td class=xl12810219>&nbsp;</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H521 Miopía<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border-top:none;border-right:.5pt solid windowtext;
  border-bottom:none;border-left:none;background:#BFBFBF;mso-pattern:black none'>1</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H520 Hipermetropía<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border:none;background:#BFBFBF;mso-pattern:
  black none'>1</td>
  <td class=xl13310219 style='font-size:10.0pt;color:red;font-weight:400;
  text-decoration:none;text-underline-style:none;text-line-through:none;
  font-family:Calibri, sans-serif;border-top:none;border-right:.5pt solid windowtext;
  border-bottom:none;border-left:none;background:#BFBFBF;mso-pattern:black none'>3</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl8710219 style='height:18.0pt'>H522 Astigmatismo</td>
  <td class=xl9810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl10810219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13110219>0</td>
  <td class=xl13310219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl9110219 style='height:18.0pt'>Z460 Prueba y ajuste de
  anteojos</td>
  <td class=xl9810219>0</td>
  <td class=xl12910219>0</td>
  <td class=xl12910219>0</td>
  <td class=xl12910219>0</td>
  <td class=xl12910219>0</td>
  <td class=xl13410219>0</td>
  <td class=xl13410219>0</td>
  <td class=xl13410219>0</td>
  <td class=xl13510219>0</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl6410219 style='height:12.75pt'>Fuente: Sistema de
  Información de Consulta Externa HIS</td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl13010219>Reporte Generado:</td>
  <td colspan=2 class=xl13910219>10/22/2016</td>
  <td class=xl6510219></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl6410219 style='height:12.75pt'>Oficina General de
  Estadística e Informática - MINSA</td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10310219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl6510219 style='height:18.0pt'></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td height=24 class=xl6510219 style='height:18.0pt'></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <tr height=0 style='display:none;mso-height-source:userset;mso-height-alt:
  360'>
  <td class=xl6510219></td>
  <td class=xl6510219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl10210219></td>
  <td class=xl6510219></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=433 style='width:325pt'></td>
  <td width=62 style='width:47pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=30 style='width:23pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->

<script src="{{ url('/node_modules/axios/dist/axios.min.js') }}"></script>
<script src="{{ url('/node_modules/vue/dist/vue.min.js') }}"></script>
<script src="{{ url('/resources/assets/js/indicadores/appOcularReporte.js') }}"></script>

</body>

</html>
